2024-10-11 18:06:30,623 | WARNING | test_run | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Pasha\Обучение\Urban_Univercity\Python-разработчик\PycharmProjects\pythonProject_homeworkM12\tests_12_4.py", line 25, in test_run
    self.name = rt_we.Runner(13)
                ^^^^^^^^^^^^^^^^
  File "D:\Pasha\Обучение\Urban_Univercity\Python-разработчик\PycharmProjects\pythonProject_homeworkM12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-11 18:06:30,624 | WARNING | test_walk | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Pasha\Обучение\Urban_Univercity\Python-разработчик\PycharmProjects\pythonProject_homeworkM12\tests_12_4.py", line 14, in test_walk
    self.name = rt_we.Runner('Ben', speed=-5)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pasha\Обучение\Urban_Univercity\Python-разработчик\PycharmProjects\pythonProject_homeworkM12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
